### ISSUE TITLE
Add Shellcheck to CI

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/ca_extend#11]
SC1090 is disabled in most files. Let's disable it globally in CI. SHELLCHECK_OPTS="--exclude SC1090" to reduce the redundant disabling of it.  shellcheck can be added to the travis-ci.yml like the following.

https://github.com/puppetlabs/support-tasks/blob/master/.sync.yml#L25-L34
https://github.com/puppetlabs/support-tasks/blob/master/.sync.yml#L48-L49
https://github.com/puppetlabs/support-tasks/blob/master/.sync.yml#L59-L62

Then run pdk update to sync the changes to the travis file.

**Comment by m0dular** [comment]
Fixed via workflow standardization in Github Actions.
