### ISSUE TITLE
ca_extend uses hardcoded paths to files and directories

### ISSUE THREAD

**Issue by Sharpie** [puppetlabs/ca_extend#14]
## Describe the Bug

The tasks and plans in the `ca_extend` module read and write various files. In some cases, hardcoded paths are used such as: `/etc/puppetlabs/puppet/ssl/`, `/etc/puppetlabs/puppet/ssl/ca/` or `/etc/puppetlabs/puppet/ssl/certs/ca.pem`.

These paths are configurable via `puppet.conf` and so the relevant settings, `ssldir`, `cadir`, `localcacert`, etc., should be read via `puppet config print`. This is especially important with the Puppet 6 -> Puppet 7 upgrade that changes the default location of `cadir` from `/etc/puppetlabs/puppet/ssl/ca/` to `/etc/puppetlabs/puppetserver/ca`.

**Comment by MartyEwings** [comment]
SUP-2446 |  
-- | --


<br class="Apple-interchange-newline">

**Comment by m0dular** [comment]
Fixed in #30
