### ISSUE TITLE
The REFERENCE.md is not inline with the puppet-strings docs

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/ca_extend#4]
The code should be updated with the correct comments for puppet-strings to automatically generate the documentation. Currently generating the REFERENCE.md will remove valuable content. 

```
pdk bundle exec rake strings:generate:reference
```

The code should be updated to comply with [puppet-strings](https://puppet.com/docs/puppet/latest/puppet_strings.html)

**Comment by MartyEwings** [comment]
Puppet-strings is called as part of the automated release workflow, so I would fix this as it will be a blocker for the release process @m0dular
