### ISSUE TITLE
Support External PE Postgres

### ISSUE THREAD

**Issue by m0dular** [puppetlabs/ca_extend#43]
In my fork of the module, we closed an issue to support split installs because they are a deprecated architecture.  However, because external PE Postgres (i.e. a dedicated postgres node managed by PE code) is a feature of PE XL, we need a solution for this.

Currently, the plan only restarts `pe-postgresql`on the primary.  In the event of an expired CA in PE XL, I'm not sure if this would fail or be enough to fix the services on the primary, but the postgres node(s) would still be down.

**Comment by MartyEwings** [comment]
within the context that the CA generated in puppet 6 or higher can not be regenerated by this tool, and all  puppet 6 CAs have a 15 year lifespan.

PE XL infras are only supported after Puppet 6, so this edge case is not worth expending effort
