### ISSUE TITLE
(SUP-2655) Bolt version needs updated

### ISSUE THREAD

**Issue by derek-robinson** [puppetlabs/ca_extend#45]
The minimum version required is incorrect and needs updated. The module wouldn't work with 1.33 and error'ed out with messages about nodes and targets not found. Upgrading to the latest version fixed the issue, but I'm not sure what the minimum would be. 

> This module requires Puppet Bolt >= 1.2.0 on either on the primary Puppet server or a workstation with connectivity to the primary.

**Comment by henrywangpuppet** [comment]
Tested the minimum supported version for --targets is 1.38.0
PR created: https://github.com/puppetlabs/ca_extend/pull/49
