### ISSUE TITLE
ca_extend::upload_ca_cert plan doesn't from from the console

### ISSUE THREAD

**Issue by jordi-garcia** [puppetlabs/ca_extend#69]
## Describe the Bug
Whenever the `ca_extend::upload_ca_cert` plan gets executed as a Bolt command, it works as expected as per below.

![Bolt implementation](https://user-images.githubusercontent.com/74347335/176884761-0b3cb868-827c-4fa8-a097-6d9664a1620c.png)

However, the same `ca_extend::upload_ca_cert` plan is executed from the console with the same details, it doesn't work and reports `Could not find file: /etc/puppetlabs/puppet/ssl/certs/ca.pem` as per below:

![ca_extend upload_ca_cert](https://user-images.githubusercontent.com/74347335/176884243-8cc828b9-c634-438f-a101-b09493e776ee.png)

## Environment
 - puppetlabs-ca_extend (v3.2.0)
 - PE 2019.8.7 and PE 2021.3

**Comment by m0dular** [comment]
I think we made a clarification in the docs that the plans don't work over Orchestrator for this reason and maybe a couple others.  If users are still able to use the Console, i.e. the cert hasn't expired yet, then managing `ca.pem` in Puppet code is probably the best option.
